version: '3'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
